
import java.util.ArrayList;
import javax.swing.JFrame;
public class Cont extends JFrame {
	public ArrayList<String>  con;
	Cont(){
		con = new ArrayList<String>();
		con.add("Afghanistan");
		con.add("Albania");
		con.add("Algeria");
		con.add("Andorra");
		con.add("Angola");
		con.add("Antigua and Barbuda");
		con.add("Argentina");
		con.add("Armenia");
		con.add("Austria");
		con.add("Azerbaijan");
		con.add("Bahrain");
		con.add("Bangladesh");
		con.add("Barbados");
		con.add("Belarus");
		con.add("Belgium");
		con.add("Belize");
		con.add("Benin");
		con.add("Bhutan");
		con.add("Bolivia");
		con.add("Bosnia and Herzegovina");
		con.add("Botswana");
		con.add("Brazil");
		con.add("Brunei");
		con.add("Bulgaria");
		con.add("Burkina Faso");
		con.add("Burundi");
		con.add("Cabo Verde");
		con.add("Cambodia");
		con.add("Cameroon");
		con.add("Canada");
		con.add("Central African Republic");
		con.add("Chad");
		con.add("Channel Islands");
		con.add("Chile");
		con.add("China");
		con.add("Colombia");
		con.add("Comoros");
		con.add("Congo");
		con.add("Costa Rica");
		con.add("Côte d'Ivoire");
		con.add("Croatia");
		con.add("Cuba");
		con.add("Cyprus");
		con.add("Czech Republic");
		con.add("Denmark");
		con.add("Djibouti");
		con.add("Dominica");
		con.add("Dominican Republic");
		con.add("DR Congo");
		con.add("Ecuador");
		con.add("Egypt");
		con.add("El Salvador");
		con.add("Equatorial Guinea");
		con.add("Eritrea");
		con.add("Estonia");
		con.add("Eswatini");
		con.add("Ethiopia");
		con.add("Faeroe Islands");
		con.add("Finland");
		con.add("France");
		con.add("French Guiana");
		con.add("Gabon");
		con.add("Gambia");
		con.add("Georgia");
		con.add("Germany");
		con.add("Ghana");
		con.add("Gibraltar");
		con.add("Greece");
		con.add("Grenada");
		con.add("Guatemala");
		con.add("Guinea");
		con.add("Guinea-Bissau");
		con.add("Guyana");
		con.add("Haiti");
		con.add("Holy See");
		con.add("Honduras");
		con.add("Hong Kong");
		con.add("Hungary");
		con.add("Iceland");
		con.add("India");
		con.add("Indonesia");
		con.add("Iran");
		con.add("Iraq");
		con.add("Ireland");
		con.add("Isle of Man");
		con.add("Israel");
		con.add("Italy");
		con.add("Jamaica");
		con.add("Japan");
		con.add("Jordan");
		con.add("Kazakhstan");
		con.add("Kenya");
		con.add("Kuwait");
		con.add("Kyrgyzstan");
		con.add("Laos");
		con.add("Latvia");
		con.add("Lebanon");
		con.add("Lesotho");
		con.add("Liberia");
		con.add("Libya");
		con.add("Liechtenstein");
		con.add("Lithuania");
		con.add("Luxembourg");
		con.add("Macao");
		con.add("Madagascar");
		con.add("Malawi");
		con.add("Malaysia");
		con.add("Maldives");
		con.add("Mali");
		con.add("Malta");
		con.add("Mauritania");
		con.add("Mauritius");
		con.add("Mayotte");
		con.add("Mexico");
		con.add("Moldova");
		con.add("Monaco");
		con.add("Mongolia");
		con.add("Montenegro");
		con.add("Morocco");
		con.add("Mozambique");
		con.add("Myanmar");
		con.add("Namibia");
		con.add("Nepal");
		con.add("Netherlands");
		con.add("Nicaragua");
		con.add("Niger");
		con.add("Nigeria");
		con.add("North Korea");
		con.add("North Macedonia");
		con.add("Norway");
		con.add("Oman");
		con.add("Pakistan");
		con.add("Panama");
		con.add("Paraguay");
		con.add("Peru");
		con.add("Philippines");
		con.add("Poland");
		con.add("Portugal");
		con.add("Qatar");
		con.add("Réunion");
		con.add("Romania");
		con.add("Russia");
		con.add("Rwanda");
		con.add("Saint Helena");
		con.add("Saint Kitts and Nevis");
		con.add("Saint Lucia");
		con.add("Saint Vincent and the Grenadines");
		con.add("San Marino");
		con.add("Sao Tome & Principe");
		con.add("Saudi Arabia");
		con.add("Senegal");
		con.add("Serbia");
		con.add("Seychelles");
		con.add("Sierra Leone");
		con.add("Singapore");
		con.add("Slovakia");
		con.add("Slovenia");
		con.add("Somalia");
		con.add("South Africa");
		con.add("South Korea");
		con.add("South Sudan");
		con.add("Spain");
		con.add("Sri Lanka");
		con.add("State of Palestine");
		con.add("Sudan");
		con.add("Suriname");
		con.add("Sweden");
		con.add("Switzerland");
		con.add("Syria");
		con.add("Taiwan");
		con.add("Tajikistan");
		con.add("Tanzania");
		con.add("Thailand");
		con.add("The Bahamas");
		con.add("Timor-Leste");
		con.add("Togo");
		con.add("Trinidad and Tobago");
		con.add("Tunisia");
		con.add("Turkey");
		con.add("Turkmenistan");
		con.add("Uganda");
		con.add("Ukraine");
		con.add("United Arab Emirates");
		con.add("United Kingdom");
		con.add("United States");
		con.add("Uruguay");
		con.add("Uzbekistan");
		con.add("Venezuela");
		con.add("Vietnam");
		con.add("Western Sahara");
		con.add("Yemen");
		con.add("Zambia");
		con.add("Zimbabwe");
	}
}